<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Form</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    <b style="color: red"><?=$flushMessage ?></b> <br>
    Email:<br>
    <input type="email" name="email" value="<?=$request->post('email')?>"> <br>

    Message:<br>
    <textarea name="message"><?=$request->post('message')?></textarea> <br>
    <input type="file" name="attachment">
    <button type="submit">GO!</button>
</form>
<hr>
<h2>Comments</h2>
<?php foreach ($comments as $comment): ?>

    <?=$comment['email']?> <?/*=$comment['data']*/?> <br>
    <?=$comment['message']?>
    <hr>
<?php endforeach; ?>
</body>
</html>